# Generated by Django 3.1.1 on 2020-10-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191213_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avi.jpg', upload_to='Profile_pics/'),
        ),
    ]
